#!/usr/bin/env python
"""AVEN brand book build steps.
  python src/build.py tokens   -> kit/tokens.css from kit/tokens.json
  python src/build.py fonts    -> assets/fonts/*.woff2 (latin only) + assets/fonts/fonts.css
  python src/build.py marks    -> kit/marks/*.svg with wordmark <text> outlined to paths (fontTools)
  python src/build.py all
Fonts are fetched from Google Fonts CSS2 with a Chrome UA so woff2 is served; only the
latin block is kept. Wordmarks are outlined from the RECOMMENDED pair by default.
"""
import os, re, sys, json, urllib.request, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
KIT = ROOT / "kit"
FONTS = ROOT / "assets" / "fonts"
SRC_MARKS = ROOT / "src" / "marks"
OUT_MARKS = ROOT / "kit" / "marks"
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"}

CANDIDATES = {  # slug: (css2 family spec, display name, kind)
    "source-serif-4": ("Source+Serif+4:opsz,wght@8..60,400..700", "Source Serif 4", "serif"),
    "crimson-pro":    ("Crimson+Pro:wght@400..700", "Crimson Pro", "serif"),
    "eb-garamond":    ("EB+Garamond:wght@400..700", "EB Garamond", "serif"),
    "nunito-sans":    ("Nunito+Sans:opsz,wght@6..12,400..700", "Nunito Sans", "sans"),
    "mulish":         ("Mulish:wght@400..700", "Mulish", "sans"),
    "inter":          ("Inter:wght@400..700", "Inter", "sans"),
}
RECOMMENDED = {"serif": "source-serif-4", "sans": "nunito-sans"}


def tokens():
    t = json.loads((KIT / "tokens.json").read_text(encoding="utf-8"))
    lines = [":root{"]
    for k, v in t["color"].items():
        lines.append(f"  --{k}:{v['hex']};")
    lines.append(f"  --font-serif:{t['type']['serif']['stack']};")
    lines.append(f"  --font-sans:{t['type']['sans']['stack']};")
    lines.append("}")
    (KIT / "tokens.css").write_text("/* generated from tokens.json - do not edit */\n" + "\n".join(lines) + "\n", encoding="utf-8")
    print("tokens.css written")


def fonts():
    FONTS.mkdir(parents=True, exist_ok=True)
    css_out = ["/* self-hosted latin subsets - Google Fonts, SIL OFL. generated by src/build.py */"]
    for slug, (spec, name, kind) in CANDIDATES.items():
        url = f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        css = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode()
        blocks = re.findall(r"/\*\s*latin\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
        if not blocks:
            sys.exit(f"no latin block for {name}")
        src = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", blocks[0]).group(1)
        data = urllib.request.urlopen(urllib.request.Request(src, headers=UA), timeout=60).read()
        fn = f"{slug}-latin.woff2"
        (FONTS / fn).write_bytes(data)
        css_out.append(f'@font-face{{font-family:"Cand {name}";src:url("{fn}") format("woff2");font-weight:400 700;font-display:swap}}')
        print(f"{name}: {len(data)//1024} KB")
    for kind, slug in RECOMMENDED.items():
        alias = "AVEN Serif" if kind == "serif" else "AVEN Sans"
        css_out.append(f'@font-face{{font-family:"{alias}";src:url("{slug}-latin.woff2") format("woff2");font-weight:400 700;font-display:swap}}')
    (FONTS / "fonts.css").write_text("\n".join(css_out) + "\n", encoding="utf-8")
    (FONTS / "OFL.txt").write_text("All fonts in this folder are licensed under the SIL Open Font License 1.1 - https://openfontlicense.org\n", encoding="utf-8")
    assert "gstatic" not in (FONTS / "fonts.css").read_text()
    print("fonts.css written")


def _font(slug, weight=400):
    from fontTools.ttLib import TTFont
    f = TTFont(str(FONTS / f"{slug}-latin.woff2"))
    if "fvar" in f:
        from fontTools.varLib.instancer import instantiateVariableFont
        loc = {}
        for a in f["fvar"].axes:
            if a.axisTag == "wght":
                loc[a.axisTag] = weight
            elif a.axisTag == "opsz":
                loc[a.axisTag] = max(a.minValue, min(16, a.maxValue))
            else:
                loc[a.axisTag] = a.defaultValue
        f = instantiateVariableFont(f, loc)
    return f


def _outline(f, text, size, spacing, cx, baseline, fill):
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    gs, cmap, hmtx = f.getGlyphSet(), f.getBestCmap(), f["hmtx"]
    upem = f["head"].unitsPerEm
    sc = size / upem
    glyphs = [cmap.get(ord(c), ".notdef") for c in text]
    total = sum(hmtx[g][0] * sc for g in glyphs) + spacing * (len(glyphs) - 1)
    x = cx - total / 2
    d = []
    for g in glyphs:
        pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
        gs[g].draw(TransformPen(pen, (sc, 0, 0, -sc, x, baseline)))
        cmds = pen.getCommands()
        if cmds:
            d.append(cmds)
        x += hmtx[g][0] * sc + spacing
    return f'<g aria-label="{text}"><path fill="{fill}" d="{" ".join(d)}"/></g>'


TEXT_RE = re.compile(
    r'<text\s+x="([\d.]+)"\s+y="([\d.]+)"\s+text-anchor="middle"\s+fill="(#[0-9a-fA-F]{6})"'
    r'\s+font-size="([\d.]+)"\s+letter-spacing="([\d.]+)"\s+font-family="[^"]*">([^<]+)</text>'
)


def marks(serif=None, sans=None, outdir=None, suffix=""):
    serif = serif or RECOMMENDED["serif"]
    sans = sans or RECOMMENDED["sans"]
    fs, fa = _font(serif), _font(sans)
    outdir = outdir or OUT_MARKS
    outdir.mkdir(parents=True, exist_ok=True)
    n = 0
    for p in sorted(SRC_MARKS.glob("*.svg")):
        svg = p.read_text(encoding="utf-8")

        def rep(m):
            x, y, fill, size, sp, txt = m.groups()
            font = fs if txt.strip() == "AVEN" else fa
            return _outline(font, txt.strip(), float(size), float(sp), float(x), float(y), fill)

        out, k = TEXT_RE.subn(rep, svg)
        assert k >= 1, f"no wordmark text matched in {p.name}"
        out = re.sub(r'<svg width="\d+" height="\d+" ', '<svg xmlns="http://www.w3.org/2000/svg" ', out, count=1)
        (outdir / f"{p.stem}{suffix}.svg").write_text(out, encoding="utf-8")
        n += 1
    print(f"outlined {n} marks -> {outdir} ({serif} / {sans})")


def candidates():
    """wordmark-only SVG in each candidate serif for the type card"""
    cdir = OUT_MARKS / "candidates"
    cdir.mkdir(parents=True, exist_ok=True)
    for slug, (_, name, kind) in CANDIDATES.items():
        if kind != "serif":
            continue
        g = _outline(_font(slug), "AVEN", 34, 5, 105, 78, "#1c2b26")
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 210 110" role="img" aria-label="AVEN wordmark in {name}">{g}'
               '<line x1="46" y1="96" x2="120" y2="96" stroke="#2e4b3f" stroke-width="1.4" stroke-linecap="round"/>'
               '<circle cx="131" cy="96" r="2.6" fill="#5b7e8c"/>'
               '<line x1="142" y1="96" x2="164" y2="96" stroke="#2e4b3f" stroke-width="1.4" stroke-linecap="round"/></svg>')
        (cdir / f"wordmark--{slug}.svg").write_text(svg, encoding="utf-8")
    print("candidate wordmarks written")


if __name__ == "__main__":
    step = sys.argv[1] if len(sys.argv) > 1 else "all"
    if step in ("tokens", "all"):
        tokens()
    if step in ("fonts", "all"):
        fonts()
    if step in ("marks", "all"):
        marks()
        candidates()
